# after updating this file, please run the following command
# so that deps are updated correctly:
#
# cargo generate-lockfile && CARGO_BAZEL_REPIN=1 bazelisk sync --only=cargo
[package]
name = "monorepo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "=4.5.13", features = ["derive"] }
swc_common = "=0.36.0"
sha2 = "=0.10.8"
hex = "=0.4.3"
serde_json = "=1.0.121"
swc_atoms = "=0.6.7"
rxp = "=0.2.0"
swc_ecma_parser = "=0.148.0"
swc_ecma_ast = "=0.117.0"
swc_allocator = "=0.1.6"
