[package]
name = "monorepo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
swc_common = "0.32.1"
sha2 = "0.10.8"
hex = "0.4.3"
serde_json = "1.0.107"
swc_atoms = "0.6.0"